# Generated by Django 2.0.1 on 2018-01-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='quited_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address_from',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='person',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='quited_at',
        ),
    ]
